steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'ls -la'
      - 'ls -ltrah'
      - 'chmod 777 ./cloudrun-rg-scaleup-min-max.sh'
      - './cloudrun-rg-scaleup-min-max.sh'
